version: "3.7"

networks:
  caddy_internal_net:
    external: true
  runner_network:
    driver: overlay
    attachable: true

volumes:
    gitlab-data:
      driver: glusterfs:latest
      name: "shared-volume/gitlab/data"
    gitlab-config:
      driver: glusterfs:latest
      name: "shared-volume/gitlab/config"
    gitlab-logs: {}
    gitlab-runner-config: {}

secrets:
  gitlab_root_password:
    file: ./root_password.txt
  # gitlab_omniauth_providers:
  #   file: ./gitlab_omniauth_providers.txt

services:
  gitlab:
    image: jmb12686/gitlab:13.1.0
    networks:
      - caddy_internal_net
      - runner_network
    volumes:
      - gitlab-data:/var/opt/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-config:/etc/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.int.belisleonline.com' # Address to access gitlab from the outside internet
        gitlab_rails['initial_root_password'] = File.read('/run/secrets/gitlab_root_password')
        ## Override default detection of the 'external_url' to enable usage of external load balancer and TLS termination
        ## https://docs.gitlab.com/omnibus/settings/nginx.html#supporting-proxied-ssl
        nginx['listen_port'] = 80
        nginx['listen_https'] = false

        # Disable Prometheus node_exporter inside Docker.
        node_exporter['enable'] = false

        ## To completely disable prometheus, and all of it's exporters, set to false
        prometheus_monitoring['enable'] = false

        ## Set Unicorn timeout and lower processes (2 is the lowest allowed at this moment)
        puma['max_threads'] = 2
        puma['min_threads'] = 1
        puma['worker_processes'] = 2
        puma['worker_timeout'] = 60

        ## Set Sidekiq timeout and lower its concurrency to the lowest allowed
        sidekiq['shutdown_timeout'] = 4
        sidekiq['concurrency'] = 5
        
        # registry_external_url 'https://registry.gitlab.int.belisleonline.com'
        # registry_nginx['listen_port'] = 5001
        # registry_nginx['listen_https'] = false

        # gitlab_rails['omniauth_providers'] = File.read('/run/secrets/gitlab_omniauth_providers')

    secrets:
      - gitlab_root_password
      # - gitlab_omniauth_providers
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 4000M
        reservations:
          memory: 2048M
    stop_grace_period: 60s
    healthcheck:
      test: ["CMD", "/opt/gitlab/bin/gitlab-healthcheck", "--fail", "--max-time", "15"]
      interval: 60s
      timeout: 30s
      retries: 8
      start_period: 4m