groups:
- name: meta
  rules:
  - alert: DeadMansSnitch
    expr: vector(1)
    labels:
      severity: critical
    annotations:
      description: This is a DeadMansSnitch meant to ensure that the entire Alerting
        pipeline is functional.
      summary: Alerting DeadMansSnitch